# application.yml
--- 
spring: 
  application: 
    name: s2
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:8761/eureka/
# leave eureka.instance.leaseRenewalIntervalInSeconds unchanged in production
# just here to provide quicker updates to Eureka for demos
#instance: 
#    leaseRenewalIntervalInSeconds: 5
#    metadataMap: 
#      instanceId: ${spring.application.name}:${random.value}
server: 
#  port: ${PORT:${SERVER_PORT:0}}
  port: 8080
words: to,pass,the,test

--- 
spring: 
  profiles: vendite
  application: 
    name: vendite
sales: 18000,16000,21000,30000,37000,150000,26000,1800000,96000
#server: 
#  port: 8080
  


